### PR TITLE
Fix for NDI AMW usage

### PR DESCRIPTION
**Pull request by brryan**
### Background

* Passing zaid=2004 to NDI_AtomicMass would cause NDI to return 7 AMWs (for zaid=2004 and other zaids like 20040)
* Tom Saller showed me how to fix this: append a "." to the zaid.

### Purpose of Pull Request

* Fix this bug by passing e.g. "2004." instead of "2004"
* [Fixes Redmine Issue #1884](https://rtt.lanl.gov/redmine/issues/1884)

### Description of changes

* Reformat the ZAID when converting from an integer before passing to NDI.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by keadyk** [comment]
LGTM! I'll wait a little longer to see if anything comes in from tt, but I'll merge soon. 

@KineticTheory the Cdash coverage build for this PR looks really weird. There's no way this PR could've caused coverage to drop by ~7%, so I'm going to ignore it... it looks like maybe the test directories are getting included for some reason. The codecov report here on GitHub looks fine!

**Comment by KineticTheory** [comment]
Let's wait for tt.  It is backlogged with a cta CI job.

**Comment by KineticTheory** [comment]
> LGTM! I'll wait a little longer to see if anything comes in from tt, but I'll merge soon.
> 
> @KineticTheory the Cdash coverage build for this PR looks really weird. There's no way this PR could've caused coverage to drop by ~7%, so I'm going to ignore it... it looks like maybe the test directories are getting included for some reason. The codecov report here on GitHub looks fine!

Yeah.  I was looking at that.  It seems that @brryan's branch is a bit out-of-date and doesn't have the exclusions for code in test directories and STL headers that I introduced in #751 and updated in #766.

**Comment by KineticTheory** [comment]
I don't consider the coverage issue to be a blocker.  It should merge cleanly.

**Comment by KineticTheory** [comment]
BTW - the trinitite CI for this PR is next in line and should start within 15 minutes.

**Comment by keadyk** [comment]
tt passing! Merging now :)

**Pull request merged**
