### PR TITLE
Add c4/global include so C4_MPI header can be used standalone

### PR DESCRIPTION
**Pull request by keadyk**
### Background

* While trying to add a new file in a different project, I found that I couldn't include c4/C4_MPI.hh without including c4/global.hh as well. Code in C4_MPI needs access to definitions in C4_Functions, C4_Datatypes, and C4_Traits, all of which become available via the c4/global.hh include.

### Purpose of Pull Request

* Add global include to C4_MPI so it can be included elsewhere standalone

### Description of changes

* one-line change. Add include.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [ ] Travis/Appveyor CI checks pass
  * [ ] Code coverage does not decrease
  * [ ] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@keadyk While your assessment is correct.  This is actually a design feature (albeit a clunky one).  You should never include `C4_MPI.hh` directly.  Please include `c4/global.hh` instead.  Otherwise, you will have a a circular reference.  See https://rtt.lanl.gov/autodoc/draco/global_8hh.html.

global_8hh__incl

**Comment by keadyk** [comment]
What?!

**Comment by KineticTheory** [comment]
I'm not sure why that diagram doesn't show that C4_Functions includes C4_MPI.  But you can see that in the source code.

**Comment by KineticTheory** [comment]
> I'm not sure why that diagram doesn't show that C4_Functions includes C4_MPI. But you can see that in the source code.

Ah - I think I need to tell doxygen the use CPP Macro `C4_MPI=1`.

**Comment by keadyk** [comment]
Ahh, it includes it at the verrrrrry bottom of the file. Not what I expected!

**Comment by KineticTheory** [comment]
Yeah - that's a pretty outdated design-pattern.

**Pull request closed without merging**
