### PR TITLE
Fix dependency link order for FortranChecks

### PR DESCRIPTION
**Pull request by KineticTheory**
*Background*

Visual Studio 2017 started to fail to build the FortranChecks tests a few days ago.  This is probably due to version upgrades for Visual Studio, CMake and MSYS gfortran on the test machine.

*Solution*

The link dependencies were provided in reverse order.  Reordering these libraries on the link line seems to fix the problem.

*Also*

Remove some old `$Id$` comments left over from the days of subversion.

* [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [x] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco) (one failure related to new MPI version and fortran code. I'll fix this in a separate PR).
  * [x] [Toss2 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by keadyk** [comment]
The ccscs2 build errors for this PR are my (Compton's) fault. Somehow, the .modulerc file on ccscs2 has the default csk version set to 0.3.0 instead of 0.2.0. I didn't create this file, so it should've just been synced over from ccscs7 (which has the correct default of 0.2.0). I'm not sure how this happened!

**Comment by keadyk** [comment]
I reran your PR on ccscs2 after manually changing the csk default version back to 0.2.0, and it looks just fine!

**Comment by KineticTheory** [comment]
The valgrind build failed because I needed to rebase.  I'll check the results tomorrow.

**Comment by KineticTheory** [comment]
@keadyk I think this is ready to be merged.

**Comment by keadyk** [comment]
Okay! I kicked off the valgrind regression for this PR one more time, because CDash shows a possible leak in Saturday's tests. (I imagine it's spurious, but since it shows up in the FortranChecks library I figure it's good to double-check.) I'll merge once results are in!

**Comment by keadyk** [comment]
Valgrind report looks clean!

**Pull request merged**
