### PR TITLE
Provide clang-tidy recommended changes

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* Process four additional components with _clang-tidy_ code transformation recommendations and add these packages to the nightly regression that processes _clang-tidy_.

### Description of changes

* Provide updates for mesh_element, ode, linear, and memory components.
* Transform `typedef` to `using` commands.
* Make use of `auto` when the data type is specified on the RHS with a `static_cast`.
* Use `<cmath>` instead of `<math.h>`
* Use `std::array` instead of C-style arrays. 
  * https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-stack
  * https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#slcon1-prefer-using-stl-array-or-vector-instead-of-a-c-array
* When possible, use C++14 style range-based for-loops.
* Big changes in mesh_element take advantage of new C++14 capabilities to reduce the amount of code.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by attom** [comment]
How automatic were these changes? Would they be straightforward to apply to the rest of draco or downstream codes?

**Comment by attom** [comment]
Are we at all worried about slow-downs for debug code when changing from C-style arrays to std::array?

https://godbolt.org/z/58oizr

**Comment by KineticTheory** [comment]
> Are we at all worried about slow-downs for debug code when changing from C-style arrays to std::array?
> 
> https://godbolt.org/z/58oizr

I don't think you can make that comparison fairly with `-O0`.  It is true that `std::array` will generate more instructions for non-optimized code. It is a full STL container after all. However, it is my understanding is that the extra instructions are almost always optimized away.  If you are concerned about this change, it might be worth checking out this PR and running your perfbench tests when linking to this updated version of Draco.

**Comment by KineticTheory** [comment]
> Are we at all worried about slow-downs for debug code when changing from C-style arrays to std::array?
> 
> https://godbolt.org/z/58oizr

@attom Interesting discussion about the performance of `std::array` is (here)[https://stackoverflow.com/questions/30263303/stdarray-vs-array-performance].

**Comment by KineticTheory** [comment]
> How automatic were these changes? Would they be straightforward to apply to the rest of draco or downstream codes?

It's a mixed bag.  I've tried to use the _automatically apply_ feature of _clang-tidy_, but that seems to usually break our tests.  All of the changes I made in this PR were applied manually.  I used _clang-tidy_ to identify blocks of code that needed review and then I made the updates.  In many cases, a cursory look at the _bad_ code allowed me to make bigger changes than noted by _clang-tidy_.

Notes:
* I'm only using a small subset of the rules that clang-tidy offers.
* I have a nightly regression that will continue to test the components that have been updated.  This is why `src/CMakeLists.txt` was modified.  The relevant [CDash report](https://rtt.lanl.gov/cdash/index.php?project=Draco) uses the build name `clang-9.0.0-clangtidy_Debug-develop`

**Comment by KineticTheory** [comment]
@till If you are interested in clang-tidy, you should review https://clang.llvm.org/extra/clang-tidy/.  I think this could be an extremely valuable tool to introduce into our normal development workflow.  I wish I could figure out how to only process new or touched code, but that doesn't seem possible right now.

These additional checks look very promising:
* `clang-analyzer-*`
* `bugprone-*`
* `performance-*`
* `readability-*`
* `cppcoreguidelines-*`

See https://rtt.lanl.gov/redmine/projects/draco/wiki/Common_Configure_Options and search for `clang-tidy` for instructions on using this linter on your own code.

**Comment by attom** [comment]
> > Are we at all worried about slow-downs for debug code when changing from C-style arrays to std::array?
> > https://godbolt.org/z/58oizr
> 
> @attom Interesting discussion about the performance of `std::array` is (here)[https://stackoverflow.com/questions/30263303/stdarray-vs-array-performance].

Thanks for the link. I would expect zero difference in release code / optimized assembly. Sounds like folks aren't overly worried about the debug / unoptimized performance differences. I'm mostly worried about our debug CI tests taking longer to run (they use -O0, right?).

**Comment by KineticTheory** [comment]
> > > Are we at all worried about slow-downs for debug code when changing from C-style arrays to std::array?
> > > https://godbolt.org/z/58oizr
> > 
> > 
> > @attom Interesting discussion about the performance of `std::array` is (here)[https://stackoverflow.com/questions/30263303/stdarray-vs-array-performance].
> 
> Thanks for the link. I would expect zero difference in release code / optimized assembly. Sounds like folks aren't overly worried about the debug / unoptimized performance differences. I'm mostly worried about our debug CI tests taking longer to run (they use -O0, right?).

I think that is a separate issue.  Good use of unit testing will mitigate cost of running CI tests in Debug mode.  I have argued for a long time that many of your project's long running tests should be moved out of the CI suite.  The proponents of CI recommend that the entire suite should run in under 10 minutes. 

Additionally, I would expect that that heap allocation (creating `std::vectors`, etc) will swamp the cost of stack allocated data like C-style arrays or `std::array`.

I do appreciate your concern and your attention to these details.  This conversation has allowed me to focus on some of the finer details and read up on industry standard practices and recommendations.

**Comment by KineticTheory** [comment]
There are test issues. See https://rtt.lanl.gov/cdash/index.php?project=Draco&date=2020-07-03&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr869. I'll get these fixed.

**Comment by till** [comment]
Please stop mentioning me. ;)

**Comment by KineticTheory** [comment]
> Please stop mentioning me. ;)

@till I apologize for including you on these discussions.  One of the devs I work with uses your github handle on other sides and I sometimes type that w/o thinking about it.

**Comment by KineticTheory** [comment]
@attom Can you take one more look at this PR and merge it?  All of our CI is passing (minus the coverage report for the diff).

**Comment by attom** [comment]
LGTM

**Pull request merged**
