### PR TITLE
Fix a bug in FindCOMPTON.cmake.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* The `FindCOMPTON.cmake` script needs to know if OpenMP is available before parsing the script.  This dependency is a bit hidden in the Draco build system and for Capsaicin and Jayenne, the OpenMP detection was done after FindCOMPTON was called. This patch fixes this issue.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis CI checks pass - [Travis is broken.](https://rtt.lanl.gov/redmine/issues/1154)
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco) - two false positives.  Will not fix since we are moving to a new MPI later this week.
  - [x] ccs-net clang build - one test fails - known issue due to new eospac version.  Will be fixed in a different PR.
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by keadyk** [comment]
Sorry I introduced this bug!! I can review and merge later this morning.

**Comment by KineticTheory** [comment]
@keadyk This is not your fault in any way.  There was a bad logic path in the build system that didn't really show up until I reordered a few things.  The corner case includes detecting OpenMP and MPI when using clang+gfortran and also wanting CSK.

**Comment by KineticTheory** [comment]
I think this is ready to be merged.  The real test will be building jayenne against this updated Draco.

**Comment by keadyk** [comment]
Valgrind reports 2 possible leaks in diagnostics_tstruntime_error... normally, I'd assume they were spurious, but the same two show up in both of the DA runs for PR 398. Looks like something MPI-related? I'm really not sure what would cause this. (I will probably go ahead and merge in a few minutes anyway.)

{
   
   Memcheck:Leak
   match-leak-kinds: possible
   fun:malloc
   fun:strdup
   fun:opal_sec_base_validate
   fun:mca_oob_usock_peer_recv_connect_ack
   fun:recv_handler
   fun:event_process_active_single_queue
   fun:event_process_active
   fun:opal_libevent2022_event_base_loop
   fun:orte_daemon
   fun:main
}
{
   
   Memcheck:Leak
   match-leak-kinds: possible
   fun:malloc
   fun:mca_oob_usock_peer_recv_connect_ack
   fun:recv_handler
   fun:event_process_active_single_queue
   fun:event_process_active
   fun:opal_libevent2022_event_base_loop
   fun:orte_daemon
   fun:main
}

**Comment by KineticTheory** [comment]
@keadyk See notes in the PR description.  I'm going to ignore these valgrind false positives for now.

**Comment by KineticTheory** [comment]
@keadyk I also removed the 'WIP' blocker.

**Comment by keadyk** [comment]
Alright, LGTM!

**Pull request merged**
