### PR TITLE
Force configure to fail if USE_CUDA=ON but no cuda is available.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* A user report identified an issue where configuring with `-DUSE_CUDA=ON` resulted in a no-cuda build because cuda wasn't available. The expected behavior should be that the configure step fails.

### Purpose of Pull Request

* [Fixes Redmine Issue #2353](https://rtt.lanl.gov/redmine/issues/2353)

### Description of changes

+ If `USE_CUDA` is not specified, look for cuda and enable cuda build mode if found.
+ If `USE_CUDA` is specified and `ON`, fail the configure step if cuda is not available.
+ If `USE_CUDA` is specified and `OFF`, do not enable Cuda even if it is available.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@alexrlongne Can you look at this PR and comment on it?  I think this will fix a reported issue related to spack-based builds.  Hopefully it won't break any expected build modes that you use.

**Comment by alexrlongne** [comment]
@KineticTheory I'm on it! Thanks KT!

**Review by alexrlongne — APPROVED** [review]

**Comment by alexrlongne** [comment]
This looks great and covers all of the cases I need.

That codecov report seems spurious, what do you want to do?

**Comment by KineticTheory** [comment]
I'm going to ignore the coverage report.  I think `develop` might be my for my fork of draco.  I should probably update that.

**Pull request merged**
