### PR TITLE
viz :: Prevent cell type duplication for cell data print

### PR DESCRIPTION
**Pull request by clevelam**
### Background

* PR857 enabled parallel domain decomposed ensight file generation. However, we were mistakenly duplicating the cell type in the cell data print on every rank. This cleans that up.

### Purpose of Pull Request

* Remove duplicate prints in cell data for parallel ensight file generation.

### Description of changes

* Update cell data to only print cell types ones. 

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by clevelam** [comment]
@keadyk this should fix the duplicate cell type data we are seeing in parallel.

**Comment by keadyk** [comment]
@clevelam Aha, excellent! I will merge as soon as some results come in :)

**Comment by KineticTheory** [comment]
@cleveland There is [valgrind badness...](https://rtt.lanl.gov/cdash/viewDynamicAnalysisFile.php?id=79865)

**Comment by KineticTheory** [comment]
The nightly regressions are starting to report and I'm seeing the same test errors in viz.  The actual bug was probably introduced in your previous PR.

**Pull request merged**
