### PR TITLE
Compton bugfix

### PR DESCRIPTION
**Pull request by keadyk**
### Background

* After #530, a warning appeared in clang about use of std::move preventing the compiler from doing copy elision.

### Purpose of Pull Request

* remove unneeded std::move() call
* revert specific csk version setting done in regression / bashrc scripts -- no longer needed, now that 0.4.0 is installed / defaulted on all relevant machines

### Description of changes

* See above :)

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@keadyk Did you intentionally remove the version number from the list of loaded modules?

**Comment by KineticTheory** [comment]
@keadyk Did you intentionally remove the version number from the list of loaded modules?

**Comment by keadyk** [comment]
I did -- before the previous Draco PR was merged, I had csk-0.4.0 installed, but left csk-0.3.2 as the default module to load (so the regressions wouldn't break). Now that the PR is merged and csk-0.4.0 is default on all relevant yellow machines, I think it's okay to go back to just csk... this way, the 0.4.1 version will be picked up as I install it! Let me know if you have concerns about this!

**Comment by KineticTheory** [comment]
@keadyk Can you review the [2018/12/11 CDash report](https://rtt.lanl.gov/cdash/index.php?project=Draco&date=2018-12-11) and address the build warnings also?

**Comment by keadyk** [comment]
@KineticTheory If you're talking about the clang warning, it's fixed. I also addressed the windows warnings (I think), but have no way to test them :)

**Comment by keadyk** [comment]
@KineticTheory This is ready. (The failing FPE trap test is fixed by the csk-0.4.1 release)

**Comment by KineticTheory** [comment]
LGTM

**Pull request merged**
