### PR TITLE
Add 3D orthogonal structure mesh type for mesh generators.

### PR DESCRIPTION
**Pull request by RyanWollaeger**
### Background

* The X3D parser supports parsing 3D meshes, but there is no generator for X3D files of 3D meshes in Draco.
* `x3d_generator` supports 3D file output, so what is needed is a 3D mesh type in **mesh_types.py**

### Purpose of Pull Request

* Add a simple orthogonal structured mesh type, to generate corresponding unstructured data.

### Description of changes

+ Add orth_3d_mesh class to mesh_types.py.
+ Add orth_3d_mesh as an option to x3d_generator.py.
+ Test 1-cell result of orth_3d_mesh in X3D parser unit test.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/cdash3/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/cdash3/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/cdash3/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by RyanWollaeger** [comment]
Sorry - forgot to run flake8 on this before submitting - will do so shortly.

**Comment by RyanWollaeger** [comment]
I should probably add a comment on how to use the x3d_generator script, e.g.:
```
To create X3D files for a 4x4x4 3D orthogonal structured mesh on domain (x,y,z) in [0,1]x[0,2]x[0,4]:

$ ./x3d_generator.py --mesh_type orth_3d_mesh --num_per_dim 4 4 4 --bnd_per_dim 0 1 0 2 0 4
```

**Comment by KineticTheory** [comment]
> 
> 
> I should probably add a comment on how to use the x3d_generator script, e.g.:
> 
> ```
> To create X3D files for a 4x4x4 3D orthogonal structured mesh on domain (x,y,z) in [0,1]x[0,2]x[0,4]:
> 
> $ ./x3d_generator.py --mesh_type orth_3d_mesh --num_per_dim 4 4 4 --bnd_per_dim 0 1 0 2 0 4
> ```

Can you add this to a `README.md` file in the `python` subdirectory?

**Comment by RyanWollaeger** [comment]
> > I should probably add a comment on how to use the x3d_generator script, e.g.:
> > ```
> > To create X3D files for a 4x4x4 3D orthogonal structured mesh on domain (x,y,z) in [0,1]x[0,2]x[0,4]:
> > 
> > $ ./x3d_generator.py --mesh_type orth_3d_mesh --num_per_dim 4 4 4 --bnd_per_dim 0 1 0 2 0 4
> > ```
> 
> Can you add this to a `README.md` file in the `python` subdirectory?

Good idea - will do!

**Comment by KineticTheory** [comment]
The markup linter flagged a couple issues with the `README.md`. Those should be easy to fix.

**Comment by RyanWollaeger** [comment]
> The markup linter flagged a couple issues with the `README.md`. Those should be easy to fix.

Thanks @KineticTheory - just tried to fix these.

**Review by KineticTheory — APPROVED** [review]

**Comment by RyanWollaeger** [comment]
Sorry - I missed one linter error - fixing now.

**Comment by KineticTheory** [comment]
If those lint warnings are confusing, here's the scoop: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

**Comment by KineticTheory** [comment]
This might be useful? https://dlaa.me/markdownlint/
I'm not sure if it uses the same rules that we have.

**Comment by RyanWollaeger** [comment]
> If those lint warnings are confusing, here's the scoop: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

This is a useful reference - thank you!

**Review by kgbudge — APPROVED** [review]

**Pull request merged**
