### PR TITLE
Improve ds++ code coverage by adding tests or removing features

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* Improve code coverage of ds++
* Related to #465 

### Description of changes

* In `Assert.cc`, Only define `check_insist` and `check_insist_ptr` if `DBC & 16`.
* Add unit tests for `rtt_dsxx::pack_vec_double(T*, T*, N)` and `rtt_dsxx::UnitTest::status()`.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@kgbudge This PR passes all tests.  It is ready for final review and merge. I'm interested in your review of how I hide the `check_insist[_ptr]` functions for regular builds.

**Comment by kgbudge** [comment]
Where do we use check_insist?

**Comment by KineticTheory** [comment]
@kgbudge `check_insist` is a drop-in replacement for the `Insist` CPP macro that activates when `DBC & 16` is true.  I don't think I have ever used it.  In fact, I was under the impression that this was your coding (but I might be wrong about that).

**Comment by KineticTheory** [comment]
@kgbudge If you are okay with this PR, I'll merge it.  Let me know.

**Comment by kgbudge** [comment]
Looks good to me. If I put in check_insist, I can't remember why at this point.

**Pull request merged**
