### PR TITLE
WIP: ACE-formatted Nuclear Data Reader

### PR DESCRIPTION
**Pull request by brryan**
### Background

* Future development in charged particle transport will require reading in tabulated nuclear data, which is commonly stored in ACE files. See Appendix F of the MCNP manual for details of the ACE file format. Having a generic reader in Draco would be a useful capability to support this effort.

### Purpose of Pull Request

* Create a library `cdi_ace` in Draco to support reading nuclear data from files and storing in memory. 
* Some unit tests are included.
* [Related to Jayenne Redmine task #1549](https://rtt.lanl.gov/redmine/issues/1549)

### Description of changes

* New library, `cdi_ace`, created, along with `tNuclear_Data` unit test. 
* Provided class, `rtt_cdi_ace::Nuclear_Data`, takes a path to an ACE file as a parameter in its constructor, and parses that ACE file. Currently only the Continuous-energy photoatomic reaction type is supported. The class provides public accessor functions for retrieving const references to internally stored data.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [ ] Travis CI checks pass
  * [ ] Code coverage does not decrease
  * [ ] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by warsa** [comment]
There is already a nuclear_data namespace our project and this will conflict.
I strongly recommend this PR be discussed with our team before it gets merged.

**Comment by keadyk** [comment]
Re-marking as WIP at least until we resolve namespace conflicts with other projects

**Comment by brryan** [comment]
This level of generality for reading ACE files is probably not necessary now, and the cp2011 files we're interested in are at the moment more like special cases anyway (and stopping power tables are not even really ACE files).

**Comment by david8dixon** [comment]
I have ace formatted tables with an ace reader implemented.

**Pull request closed without merging**
