### PR TITLE
2020 Copyright update

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* Update copyright date ranges to include 2020.
* Also adjust divider lines to be 80 columns.
* [x] #717 should be merged first.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@jhchang-lanl This is ready.  It can be merged whenever (changes are limited to comment blocks).

**Comment by jhchang-lanl** [comment]
@KineticTheory Are you sure it's only limited to comment blocks?

**Comment by KineticTheory** [comment]
Looks like my changes got mixed up with another commit.  Let me rebase.

**Comment by KineticTheory** [comment]
@jhchang-lanl Rebase fixed the issue of extra code found in the change-set.

**Pull request merged**
