### PR TITLE
Prefix sum on arrays

### PR DESCRIPTION
**Pull request by alexrlongne**
+ Add prefix sums on arrays to the C4 library
+ Test prefix sums on arrays in tstReduction.cc

* Purpose of Pull Request
  * Provide prefix sums on arrays (sorry for the rider). This gives `prefix_sum` similar behavior to other `global_sum` functions in c4 now.

* [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [ ] Travis CI checks pass
  * [ ] Code coverage does not decrease
  * [ ] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Toss2 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@alexrlongne Can you fix the build warnings reported by Travis?

**Comment by KineticTheory** [comment]
@along Can you also rebase against develop?

**Comment by alexrlongne** [comment]
@KineticTheory Done.

**Comment by KineticTheory** [comment]
@alexrlongne I'm still seeing 6 warnings on Travis and on ccs-net machines:
```
warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

**Pull request merged**
