### PR TITLE
On snow, change gcc640 regression to gcc740.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* gcc-7.4.0 is now a 'production' compiler on CTS-1 machines.  Update nightly regression scripts to build with gcc-7.4.0 instead of gcc-6.4.0.
* With this PR, when on CTS-1 machines always use MKL as the LAPACK provider (even when CXX=g++).  Previously we used netlib-lapack.

### Purpose of Pull Request

* [Fixes Redmine Issue #1424](https://rtt.lanl.gov/redmine/issues/1424)

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
Marking as "WIP". There are issues with newer MKL.  See https://rtt.lanl.gov/redmine/issues/1424 for details

**Comment by KineticTheory** [comment]
Ready enough.  There are a couple of tweaks that I will hold off on for another PR.

**Comment by KineticTheory** [comment]
@RyanWollaeger Do you have time to review/merge this PR?

**Comment by RyanWollaeger** [comment]
@KineticTheory Certainly.

**Pull request merged**
