### PR TITLE
Fix a couple of clang-tidy warnings.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* These are showing up on the CDash report.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@along The remaining CI finished.  This can be merged when you have time.

**Comment by alexrlongne** [comment]
@KineticTheory One build fails with an NDI error. It may be spurious but I don't see it on any other builds right now. What do you think?
https://rtt.lanl.gov/cdash/viewTest.php?onlyfailed&buildid=28258

**Comment by KineticTheory** [comment]
> @KineticTheory One build fails with an NDI error. It may be spurious but I don't see it on any other builds right now. What do you think?
> https://rtt.lanl.gov/cdash/viewTest.php?onlyfailed&buildid=28258

I think we can safely ignore that one.  I didn't touch code anywhere near that error.  I'm keeping a record of failures.  If that one pops up again, I'll ask @brryan to test it under a `fulldiagnostics` (fpe trap) build.

**Comment by alexrlongne** [comment]
Thanks for the quick response! Merged.

**Pull request merged**
