### PR TITLE
Update some comments to use 100 columns.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* Non-code cleanup after adopting a 100-column wide format.

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@alexrlongne As we discussed earlier this week.  I am processing the comment blocks for the new 100 column format.

**Comment by KineticTheory** [comment]
@alexrlongne This is ready for review whenever you have time.

**Comment by alexrlongne** [comment]
@KineticTheory I'm on it!

**Review by alexrlongne — APPROVED** [review]

**Comment by alexrlongne** [comment]
@KineticTheory Looks good. Can you fix the conflicting file?

**Comment by KineticTheory** [comment]
Sorry about the conflicting file.  I think I made the same fix in the PR that @jhchang-lanl merged this morning.  The only conflict is in a comment block.  If the autodoc CI report is clean, I think this will be safe to merge.

**Pull request merged**
